### ISSUE TITLE
nb_style not working

### ISSUE THREAD

**Issue by luissolanodev** [Yagua/nebulous.nvim#10]
Hey bro! currently setting nb_style with lua option is taking no effect. This my set up:

Installed with packer.nvim:
![image](https://user-images.githubusercontent.com/29529436/128663452-95182cf1-01ff-457c-935f-91faadf5ead3.png)

lua/plugins/nebulous.lua:
![image](https://user-images.githubusercontent.com/29529436/128663788-3c784340-5e5e-470c-b05a-a12b9879d595.png)

all the other options work except for nb_style, however loading the colorscheme with `vim.cmd("colorscheme nebulous")` works

I may be doing something wrong with my config though, just wanted to know if anyone can reproduce this, thanks in advance!

**Comment by Yagua** [comment]
Hello buuddy, how are you?
Recently an update was made in the setup function where apparently this bug was solved, I show you an example of use:

```lua
--Nebulous Settings
require("nebulous").setup {
  variant = "midnight",
  disable = {
    background = false,
  },
  italic = {
    comments   = true,
    keywords   = false,
    functions  = true,
    variables  = false,
  },
}
```

It would be good for you to take a look
