### ISSUE TITLE
Support for nvim-bufferline

### ISSUE THREAD

**Issue by luissolanodev** [Yagua/nebulous.nvim#12]
Hey! what about adding support for people using [nvim-bufferline](https://github.com/akinsho/nvim-bufferline.lua) so their tabs can be stylished and look as good as this:
![image](https://user-images.githubusercontent.com/29529436/129754804-e03d7abe-e191-4d25-a911-cef91a8ffe00.png)
 
I think the main highlight groups required are `BufferLineBufferSelected` (selected buffer). `BufferLineBufferBackground` (hidden buffer), `BufferLineFill` (tabline background color) and the corresponding to the close buttons and separators.

I tried myself but I can't get creative on them :(

**Comment by Yagua** [comment]
support added in 1503e56
