### ISSUE TITLE
Lualine Nebulous Theme Errors

### ISSUE THREAD

**Issue by dedguy21** [Yagua/nebulous.nvim#16]
neovim 0.7
tree-sitter 0.20.2
Arch Linux 

All other Lualine themes work, so I assume it's not a Lualine issue, but specific to nebulous theme interaction with lualine.

(Side note -- commenting out the first line of the lualine nebulous theme causes error to stop -- but reverts lualine to using 'auto' theme instead of nebulous)

Whenever I try to include the lualine nebulous theme I get the following errors (which I don't get with other themes):

E5108: Error executing lua /usr/share/nvim/runtime/lua/lualine/highlight.lua:99: Vim(highlight):E411: highlight group not 
found: lualine_b_normal
stack traceback:
        [C]: in function 'cmd'
        /usr/share/nvim/runtime/lua/lualine/highlight.lua:99: in function 'highlight'
        /usr/share/nvim/runtime/lua/lualine/highlight.lua:115: in function 'create_highlight_groups'
        /usr/share/nvim/runtime/lua/lualine.lua:251: in function 'setup_theme'
        /usr/share/nvim/runtime/lua/lualine.lua:285: in function 'reset_lualine'
        /usr/share/nvim/runtime/lua/lualine.lua:304: in function </usr/share/nvim/runtime/lua/lualine.lua:300>            
Type  :qa  and press <Enter> to exit Nvim

**Comment by Yagua** [comment]
Hello, I hope you are doing very well.
Thank you for reporting this dilemma. 
The error was corrected in 1165f48, I would appreciate if you could validate it.

**Comment by dedguy21** [comment]
Tested... It works now. 

Thanks
