### ISSUE TITLE
Support for lualine

### ISSUE THREAD

**Issue by luissolanodev** [Yagua/nebulous.nvim#2]
Hi! I love this theme and would like to use it everywhere in my terminal.

Do you think support for [lualine.nvim](https://github.com/hoob3rt/lualine.nvim) could be added?

**Comment by Yagua** [comment]
Hello friend, thanks for your observation regarding the colorscheme, I appreciate it!!! 
Of course, I will be working on it soon, or if you want you can do your PR to contribute with this good feature, remember you can do it.
this aspect will be in the theme sooner than you expect, again, thanks.

**Comment by LuisxSullivaN** [comment]
@DilanGMB thanks for your response!! And yeah I think I'm doing so, I actually saw details in syntax highlighting for markdown too like italics, so I'm very excited to contribute for this project!
