### ISSUE TITLE
Italic Stuff

### ISSUE THREAD

**Issue by arpangreat** [Yagua/nebulous.nvim#4]
Hello 🤗 , for 3 months nightbuddy is my favourite colorscheme ... and I am loving it ❤️ 

All though is there any way to have Italic Functions, Keywords and Variables in nightbuddy ?? It'll be really helpful if you help me 😊😊

Thanks for creating such a great colorscheme ❤️❤️😍

**Comment by Yagua** [comment]
Hello @arpangreat!, first of all thank you very much for your support, knowing that it is a good colorscheme motivates me to keep working on it. On the other hand, of course, we are working on improving the colorscheme and we are writing it 100% in lua without dependence on the Colorbuddy library, and this you mention is a feature that comes with this update. I hope you have some patience and remember that all PR is welcome.

**Comment by arpangreat** [comment]
Absolutely @DilanGMB , I will remain patience as nightbuddy is a great colorscheme ❤️🤗

And yeah in the future I will try to make this colorscheme feature full by myself too ❤️ 

Again Nightbuddy is my most favourite colorscheme rn ❤️ Thanks for making it ...

**Comment by Yagua** [comment]
Update applied, it would be good for you to take a look at it.
I will be attentive to any comments or suggestions. :)

**Comment by arpangreat** [comment]
Ayyy Now this colorscheme looks sooooo Sick!!! man 🔥🔥❤️

Gotta say it's hard enough to move eyes from it .... ❤️❤️

Looking forward for more sick updates
